---
title: "R Notebook"
output: html_notebook
---

# Grab Table set
```{r}
library(rvest)
# load dplyr
library(dplyr)

# set the page code as a vector
pages <- c(1 ,41, 81, 121, 161, 201, 241) # seq(from=1, 241, by=40)

# create a vector for url
for (i in pages){
    if (i >= 2) {
    url <- append(url, sprintf("http://www.espn.com/nba/statistics/player/_/stat/scoring-per-game/sort/avgPoints/count/%s", i))}else{
      url <- sprintf("http://www.espn.com/nba/statistics/player/_/stat/scoring-per-game/sort/avgPoints/count/%s", i)}
}

# for loop to sort through pages
for (num in 1:7){
  nba_player_data <- read_html(url[num]) %>% # url1 was created before for loop. 
        html_nodes(".tablehead") %>%
        html_table(header=TRUE)
        # get raw dataframe and set to variable
        nba_player_data <- nba_player_data[[1]]
        # drops "RK column"
        nba_player_data <- nba_player_data[, -c(1)]
        # drops row with "PLAYER" in it to remove headers from rows
        nba_player_data <- nba_player_data[!(nba_player_data$PLAYER=="PLAYER"), ]
        # write cleaned_data to a csv file
        write.csv(nba_player_data, file=sprintf("players_%s.csv", num))
    }


```
# Load dataset and bind them together

```{r}
for (i in 1:7){
  # binds new files by the row to create a bigger file
  if (i >= 2){
    grab_nba_data <- read.csv(file=sprintf("players_%s.csv", i))
    final_data <- final_data %>% 
      rbind(grab_nba_data)
  }else{
  # handles first file and reads it  
  load_nba_data <- read.csv(file=sprintf("players_%s.csv", i))
  final_data <- load_nba_data
  }
}

head(final_data)
```

# inspect new data frame
```{r}

# drop x column
final_data <- final_data[, -(1)]

# saved scraped data
write.csv(final_data, file="/Users/pythagoras/R Files/Datasets/Scraped NBA Players.csv", row.names=FALSE)

# grab position from Player column
final_data <- separate(final_data, col=c("PLAYER"), into=c("Player", "POS"), sep=",")

# remove white spaces from POS column
final_data$POS <- trimws(final_data$POS)

head(final_data)
```

# Visualize players
```{r}
# create function to plot any team
nba_data_plot <- function(team){
ggplot(data=filter(final_data, TEAM==as.character(sprintf('%s',team))), aes(x=PLAYER, y=PTS, col=PLAYER, fill=PLAYER, label=PTS)) +
  geom_col() +
  geom_text(nudge_y = 1) +
  ggtitle(sprintf("%s Points Per Game", team)) +
  theme(axis.text.x = element_text(angle = 75, hjust = 1, size=7))}

# Look at Laker's Players PPG(Points Per Game)
nba_data_plot('LAL')
```

```{r}
# Look at GS(Golden State Warriors)
nba_data_plot('GS')
```

```{r}
nba_data_plot('CLE')
```

