---
title: "R Notebook"
output: html_notebook
---
Web Scraping and Cleaning Real Estate Data
```{r}
# web scraping with rvest
library(rvest)

# real estate scraper

real_estate_html <- read_html("https://www.coldwellbankerhomes.com/ny/brooklyn/")
```

```{r}
# scrapes for data using the name of the html tag
city_zip_st <- real_estate_html %>%
  html_nodes(".city-st-zip") %>%
  html_text()
head(city_zip_st)
```

```{r}
property_values <- real_estate_html %>%
  html_nodes(".price-normal") %>% 
  html_text()
head(property_values)
```

```{r}
property_names <- real_estate_html %>%
  html_nodes(".street-address") %>%
  html_text() # grabs the text
head(property_names)
```

```{r}
# create a dataframe
combined_scraped_data <- data.frame(property_names, property_values, city_zip_st)

head(combined_scraped_data)
# save it to a csv
write.csv(combined_scraped_data, file="/Scraped_Coldwell_Data.csv")
```

```{r}
df <- read.csv("/Scraped_Coldwell_Data.csv")
```

# Inspect Dataset

```{r}
head(df, 10) # look at the first 10 rows
```

```{r}
tail(df, 10) # look at the last 10 rows
```

```{r}
# drop x column
df <- df[, -c(1)]
head(df)
```

# Clean Data
```{r}
# convert column to string
df$property_values <- as.character(df$property_values) 

# clean property values column, remove dollar sign, commas then covert to float
df$property_values <- as.numeric(gsub(",", "", substr(df$property_values, 2, nchar(df$property_values))))

head(df)
```

```{r}
library(dplyr) # data cleaning
library(tidyr) # spread, unite, gather, separate

# separate by commas
df <- separate(df, col=c("city_zip_st"), into=c("City", "State"), sep=",")
head(df, 10)
```


```{r}
head(df$State)
# trim space from left and right of strings
df$State <- trimws(df$State)


# seperate state from zip code
df <- separate(df, col=c("State"), into=c("State", "Zip"), sep=" ") 

# see new columns
head(df, 10)
```

```{r}
# Convert property names to string and remove any whitespace
# df$property_names <- trimws(as.character(df$property_names), which=c('both'))
df$property_names <- substr(df$property_names, 1, nchar(df$property_names)-1)

# inspect new column to see rows removed
df$property_names
```

# Visualization

```{r}
# Graph property values
ggplot(data=df) +
  geom_col(aes(x=property_names, y=property_values, col=property_names)) +
  theme(axis.text.x=element_text(angle=75, hjust=1, size=7))

```

```{r}
# Group by zipcode
zip_code_vaues <- df[, c("Zip", "property_values")] %>%
  group_by(Zip) %>%
  summarise(`Property_Values`=sum(property_values)) 

head(zip_code_vaues)
```

```{r}
# graph by zipcode
# load plotly
library(plotly)
ggplotly(ggplot(data=zip_code_vaues) +
  geom_col(aes(x=Zip, y=Property_Values, col=Zip, fill=Zip)) +
  ggtitle("Property Values by Zip Code") +
  theme(axis.text.x = element_text(angle=70, hjust=1, size=7)) + 
  scale_y_continuous(name="Property Values", labels = scales::comma))
```

